# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - pip-cache
    - vendor/

before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip ruby-dev
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - python3 -V  # Print out python version for debugging
  - pip3 install --upgrade pip
  - echo $CI_COMMIT_TAG
  - bundle install

stages:
  - test
  - deploy
  
pytest:
  stage: test
  script:
    - pip3 install tox setuptools docutils
    - tox -e py
  artifacts:
    paths:
      - test-results
      - htmlcov
    reports:
      junit: test-results/*.xml

flake8:
  stage: test
  script:
    - pip3 install tox setuptools docutils
    - tox -e flake8
  artifacts:
    paths:
      - test-results

rtd_doc:
  stage: test
  script:
    - pip3 install -r docs/requirements.txt
    - python3 setup.py develop
    - python3 setup.py doc
    - mv docs/_build/html htmldoc
  artifacts:
    paths:
      - htmldoc

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv htmlcov public/
    - mv htmldoc public/
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master

